# Generated by Django 5.0.14 on 2026-08-08 21:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['activo', 'inactivo'])), name='ck_equipo_estado_valido'),
        ),
    ]
