# Generated by Django 5.0.14 on 2026-08-08 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('materia', models.CharField(max_length=150)),
                ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad')),
                ('salon', models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.salon')),
            ],
            options={
                'db_table': 'programacion',
            },
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.CheckConstraint(check=models.Q(('fecha_inicio__lt', models.F('fecha_fin'))), name='ck_semestre_fechas_validas'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='semestre',
            field=models.ForeignKey(db_column='semestre_id', on_delete=django.db.models.deletion.PROTECT, to='programacion.semestre'),
        ),
        migrations.AddIndex(
            model_name='programacion',
            index=models.Index(fields=['salon', 'dia'], name='idx_programacion_salon_dia'),
        ),
        migrations.AddConstraint(
            model_name='programacion',
            constraint=models.CheckConstraint(check=models.Q(('dia__in', ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'])), name='ck_programacion_dia_valido'),
        ),
        migrations.AddConstraint(
            model_name='programacion',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='ck_programacion_horario_valido'),
        ),
    ]
