# Generated by Django 5.0.14 on 2026-08-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='docente',
            field=models.ForeignKey(blank=True, db_column='docente_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad'),
        ),
    ]
