# Generated by Django 5.0.14 on 2026-08-08 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'bloque',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='TipoSilleteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_silleteria',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('permite_prestamo_llaves', models.BooleanField(default=True)),
                ('permite_devolucion_llaves', models.BooleanField(default=True)),
                ('permite_prestamo_equipos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad_sillas', models.IntegerField(default=0)),
                ('cantidad_mesas', models.IntegerField(default=0)),
                ('bloque', models.ForeignKey(db_column='bloque_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.bloque')),
                ('tipo_silleteria', models.ForeignKey(db_column='tipo_silleteria_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.tiposilleteria')),
            ],
            options={
                'db_table': 'salon',
            },
        ),
        migrations.AddConstraint(
            model_name='salon',
            constraint=models.UniqueConstraint(fields=('nombre', 'bloque'), name='uq_salon_nombre_bloque'),
        ),
    ]
