# Generated by Django 5.0.14 on 2026-08-09 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
        ('comunidad', '0001_initial'),
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSemestral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grupo_id', models.UUIDField()),
                ('creado_manualmente', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.salon')),
                ('semestre', models.ForeignKey(db_column='semestre_id', on_delete=django.db.models.deletion.PROTECT, to='programacion.semestre')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad')),
            ],
            options={
                'db_table': 'reserva_semestral',
                'indexes': [models.Index(fields=['salon', 'dia'], name='idx_reserva_sem_salon_dia'), models.Index(fields=['grupo_id'], name='idx_reserva_semestral_grupo')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservasemestral',
            constraint=models.CheckConstraint(check=models.Q(('dia__in', ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo'])), name='ck_reserva_semestral_dia_valido'),
        ),
        migrations.AddConstraint(
            model_name='reservasemestral',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='ck_reserva_semestral_horario_valido'),
        ),
    ]
