# Generated by Django 5.0.14 on 2026-08-08 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('id_carnet', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=30, null=True)),
                ('facultad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_persona', models.ForeignKey(db_column='tipo_persona_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipopersona')),
            ],
            options={
                'db_table': 'comunidad',
            },
        ),
        migrations.AddConstraint(
            model_name='comunidad',
            constraint=models.UniqueConstraint(condition=models.Q(('id_carnet__isnull', False)), fields=('id_carnet',), name='idx_comunidad_id_carnet'),
        ),
    ]
