# Generated by Django 5.0.14 on 2026-08-08 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email_institucional', models.CharField(max_length=150, unique=True)),
                ('oid_microsoft', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.rol')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
