# Generated by Django 5.0.14 on 2026-08-09 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
        ('comunidad', '0001_initial'),
        ('novedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(choices=[('programacion', 'Programación'), ('reserva_semestral', 'Reserva semestral'), ('reserva_individual', 'Reserva individual'), ('manual', 'Manual')], max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('credencial', 'Credencial'), ('manual', 'Manual')], max_length=10)),
                ('tipo_devolucion', models.CharField(blank=True, choices=[('credencial', 'Credencial'), ('manual', 'Manual')], max_length=10, null=True)),
                ('fecha_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_prestamo', 'En préstamo'), ('demora_entrega', 'Demora en la entrega'), ('entregado', 'Entregado')], default='en_prestamo', max_length=15)),
                ('docente_titular', models.ForeignKey(db_column='docente_titular_id', on_delete=django.db.models.deletion.PROTECT, related_name='llaves_como_docente_titular', to='comunidad.comunidad')),
                ('novedad', models.ForeignKey(blank=True, db_column='novedad_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='novedades.novedad')),
                ('reclamado_por', models.ForeignKey(db_column='reclamado_por_id', on_delete=django.db.models.deletion.PROTECT, related_name='llaves_como_reclamado_por', to='comunidad.comunidad')),
                ('salon', models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.salon')),
                ('ubicacion_devolucion', models.ForeignKey(blank=True, db_column='ubicacion_devolucion_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llaves_con_devolucion_aqui', to='catalogos.ubicacion')),
                ('ubicacion_entrega', models.ForeignKey(db_column='ubicacion_entrega_id', on_delete=django.db.models.deletion.PROTECT, related_name='llaves_con_entrega_aqui', to='catalogos.ubicacion')),
                ('usuario_entrega', models.ForeignKey(db_column='usuario_entrega_id', on_delete=django.db.models.deletion.PROTECT, related_name='llaves_entregadas', to='usuarios.usuario')),
                ('usuario_recibe', models.ForeignKey(blank=True, db_column='usuario_recibe_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llaves_recibidas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'llave',
                'indexes': [models.Index(fields=['estado'], name='idx_llave_estado')],
            },
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['en_prestamo', 'demora_entrega', 'entregado'])), name='ck_llave_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.CheckConstraint(check=models.Q(('origen__in', ['programacion', 'reserva_semestral', 'reserva_individual', 'manual'])), name='ck_llave_origen_valido'),
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.CheckConstraint(check=models.Q(('tipo_entrega__in', ['credencial', 'manual'])), name='ck_llave_tipo_entrega_valido'),
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.CheckConstraint(check=models.Q(('tipo_devolucion__in', ['credencial', 'manual']), ('tipo_devolucion__isnull', True), _connector='OR'), name='ck_llave_tipo_devolucion_valido'),
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.CheckConstraint(check=models.Q(('fecha_hora_devolucion__isnull', True), ('fecha_hora_devolucion__gt', models.F('fecha_hora_entrega')), _connector='OR'), name='ck_llave_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='llave',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'entregado'), _negated=True), fields=('salon',), name='idx_llave_activa_unica_por_salon'),
        ),
    ]
