# Generated by Django 5.0.14 on 2026-08-09 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_reclamada', 'No reclamada')], default='aprobada', max_length=15)),
                ('salon', models.ForeignKey(db_column='salon_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.salon')),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad')),
            ],
            options={
                'db_table': 'reserva_individual',
                'indexes': [models.Index(fields=['salon', 'fecha'], name='idx_reserva_indiv_salon_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservaindividual',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['aprobada', 'cancelada', 'completada', 'no_reclamada'])), name='ck_reserva_individual_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='reservaindividual',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='ck_reserva_individual_horario_valido'),
        ),
    ]
