# Generated by Django 5.0.14 on 2026-08-08 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('limite_antes_mora_minutos', models.IntegerField(default=120)),
                ('max_reintentos_recordatorio', models.IntegerField(default=3)),
                ('plantilla_recordatorio', models.TextField(blank=True, null=True)),
                ('ubicacion_defecto', models.ForeignKey(db_column='ubicacion_defecto_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion')),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
    ]
