# Generated by Django 5.0.14 on 2026-08-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='limite_no_reclamada_minutos',
            field=models.IntegerField(default=30),
        ),
    ]
