# Generated by Django 5.0.14 on 2026-08-09 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_seed_catalogos_iniciales'),
        ('comunidad', '0001_initial'),
        ('equipos', '0001_initial'),
        ('novedades', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('parcialmente_devuelto', 'Parcialmente devuelto'), ('completamente_devuelto', 'Completamente devuelto')], default='activo', max_length=22)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad')),
                ('ubicacion', models.ForeignKey(db_column='ubicacion_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion')),
                ('usuario_prestamista', models.ForeignKey(db_column='usuario_prestamista_id', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'prestamo',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_completa', models.BooleanField(default=False)),
                ('ubicacion', models.ForeignKey(db_column='ubicacion_id', on_delete=django.db.models.deletion.PROTECT, to='catalogos.ubicacion')),
                ('usuario_recibe', models.ForeignKey(db_column='usuario_recibe_id', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', on_delete=django.db.models.deletion.PROTECT, to='prestamos.prestamo')),
            ],
            options={
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_equipo', models.CharField(choices=[('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='entregado', max_length=10)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo')),
                ('novedad', models.ForeignKey(blank=True, db_column='novedad_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='novedades.novedad')),
                ('prestamo', models.ForeignKey(db_column='prestamo_id', on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestamo')),
            ],
            options={
                'db_table': 'detalle_prestamo',
            },
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado'], name='idx_prestamo_estado'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['activo', 'parcialmente_devuelto', 'completamente_devuelto'])), name='ck_prestamo_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='detalleprestamo',
            constraint=models.CheckConstraint(check=models.Q(('estado_equipo__in', ['entregado', 'devuelto'])), name='ck_detalle_prestamo_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='detalleprestamo',
            constraint=models.CheckConstraint(check=models.Q(('fecha_devolucion__isnull', True), ('fecha_devolucion__gt', models.F('fecha_entrega')), _connector='OR'), name='ck_detalle_prestamo_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='detalleprestamo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado_equipo', 'entregado')), fields=('equipo',), name='idx_equipo_entregado_unico'),
        ),
    ]
