# Generated by Django 5.0.14 on 2026-08-09 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('dano', 'Daño'), ('perdida', 'Pérdida'), ('otro', 'Otro')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(db_column='registrado_por_id', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'novedad',
            },
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=models.CheckConstraint(check=models.Q(('categoria__in', ['dano', 'perdida', 'otro'])), name='ck_novedad_categoria_valida'),
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['abierta', 'cerrada'])), name='ck_novedad_estado_valido'),
        ),
    ]
