# Generated by Django 5.0.14 on 2026-08-09 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recordatorio', 'Recordatorio'), ('vencimiento', 'Vencimiento'), ('manual', 'Manual')], max_length=20)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado_envio', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido')], default='enviado', max_length=10)),
                ('destinatario', models.ForeignKey(db_column='destinatario_id', on_delete=django.db.models.deletion.PROTECT, to='comunidad.comunidad')),
                ('enviado_por', models.ForeignKey(blank=True, db_column='enviado_por_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(check=models.Q(('tipo__in', ['recordatorio', 'vencimiento', 'manual'])), name='ck_notificacion_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(check=models.Q(('estado_envio__in', ['enviado', 'fallido'])), name='ck_notificacion_estado_envio_valido'),
        ),
    ]
