# Generated by Django 5.0.14 on 2026-08-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='numero_intento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prestamo',
            field=models.ForeignKey(blank=True, db_column='prestamo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='prestamos.prestamo'),
        ),
    ]
