# Generated by Django 5.0.14 on 2026-08-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
        ('llaves', '0001_initial'),
        ('notificaciones', '0002_agregar_prestamo_numero_intento_fecha_hora'),
        ('prestamos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='llave',
            field=models.ForeignKey(blank=True, db_column='llave_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='llaves.llave'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(check=models.Q(('llave__isnull', False), ('prestamo__isnull', False), _negated=True), name='ck_notificacion_correlacion_unica'),
        ),
    ]
