# Generated by Django 5.0.14 on 2026-08-08 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('materia', models.CharField(max_length=150)),
                ('aula', models.CharField(blank=True, max_length=30, null=True)),
                ('dia', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, null=True)),
                ('horario', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('docente_titular', models.ForeignKey(db_column='docente_titular_id', on_delete=django.db.models.deletion.PROTECT, related_name='monitorias_como_docente_titular', to='comunidad.comunidad')),
                ('monitor_delegado', models.ForeignKey(db_column='monitor_delegado_id', on_delete=django.db.models.deletion.PROTECT, related_name='monitorias_como_monitor_delegado', to='comunidad.comunidad')),
            ],
            options={
                'db_table': 'monitor',
            },
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(check=models.Q(('dia__in', ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']), ('dia__isnull', True), _connector='OR'), name='ck_monitor_dia_valido'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(check=models.Q(('docente_titular_id', models.F('monitor_delegado_id')), _negated=True), name='ck_monitor_docente_distinto_de_monitor'),
        ),
    ]
